server:
  port: 8081
spring:
  cloud:     config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/ChristianRaulRamirez/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service